swagger: "2.0"
info:
  title: VPI Triangle API
  version: "1.0.0"
  description: VPI Triangle API
paths:
  /users:
    get:
      summary: Returns a list of users for authenticated users
      responses:
        200:
          description: A JSON array of user names
          schema:
            type: array
            items:
              type: string
  /users/public:
    get:
      summary: Returns a list of users for unauthenticated viewers
      responses:
        200:
          description: A JSON array of user names
          schema:
            type: array
            items:
              type: string
  /users/:id:
    get:
      summary: Returns a user
      responses:
        200:
          description: A JSON array of user names
          schema:
            type: array
            items:
              type: string

  /users/create:
    post:
      summary: Creates a user
      responses:
        200:
          description: The newly created user
          schema:
            type: array
            items:
              type: string

  /users/delete:
    delete:
      summary: Deletes a user
      responses:
        200:
          description: Confirmation of deletion
          schema:
            type: string
            items:
              type: string

  /users/update:
    put:
      summary: Modifies an existing user
      responses:
        200:
          description: The newly modified user
          schema:
            type: array
            items:
              type: string

